### ISSUE TITLE
Change display behavior of "Standings" to include per race details

### ISSUE THREAD

**Issue by jyundt** [jyundt/oval#1]
Currently, "Standings" (e.g. team, MAR, individual) are displayed as a simple sum:

![image](https://cloud.githubusercontent.com/assets/5204426/15297942/e0ef56ac-1b6a-11e6-8816-8805ab97d1f0.png)

These should be changed to display the individual results from reach race **and** the sum:

![image](https://cloud.githubusercontent.com/assets/5204426/15297972/07222be2-1b6b-11e6-95b2-7bb07b67baf8.png)

**Comment by jyundt** [comment]
Adding @mmaps to the issue.

Mike, I need help trying to get a "running tally" of the points broken down by race date.

**Comment by mmaps** [comment]
Added branch per-race-output-dev. Check it out.

**Comment by jyundt** [comment]
I took a quick look and this seems pretty promising. Thanks for doing this!

I think a few style changes are needed in the template (the Year button seems to be off), I'll probably ask @emilywools for help.
