### ISSUE TITLE
Provide an easy way to get recent data dumps

### ISSUE THREAD

**Issue by johnwheffner** [jyundt/oval#30]
For development, you usually want a copy of the current production database.  Let's make it easy to grab a dump and load it in.

**Comment by jyundt** [comment]
I've typically SCPed one of the backups from PRD -> local dev.

How would you like to get this data? Backup/restore from S3?

**Comment by johnwheffner** [comment]
We could do it that way, or possibly in the application itself using something like [sqlalchemydumps](https://github.com/cuducos/alchemydumps).  That has the benefit that it could work across different database back-ends.

**Comment by johnwheffner** [comment]
Though if you _can_ regularly upload somewhere public, that would make this less of a priority for me.

**Comment by jyundt** [comment]
Eh, I don't know if we can do something truly public; the DB dumps contains sensitive information (usernames, email addresses, passwords).

**Comment by johnwheffner** [comment]
Fair enough; at least something "superadmins" can access.

**Comment by jyundt** [comment]
alchemydumps looks good, but I think we'll hit this defect: https://github.com/cuducos/alchemydumps/issues/13

Any chance you could fix that? ;-)

**Comment by johnwheffner** [comment]
I saw that.  I also poked at alchemydumps a bit and it's not exactly what
we'd want, anyway, so I would probably just use a similar technique not the
actual code.

**Comment by jyundt** [comment]
@johnwheffner 

This is kinda clunky, but I added a "download DB" button to the Admin toolbar:

![image](https://cloud.githubusercontent.com/assets/5204426/17909558/ff5eedc4-6952-11e6-95af-a3aa334a2de9.png)

Will that work?

**Comment by johnwheffner** [comment]
Thanks, I'll try it out later.

**Comment by johnwheffner** [comment]
Though I think this is currently the only thing tying this application
specifically to postgresql.

**Comment by jyundt** [comment]
@johnwheffner Agreed, this is _very_ postgres specific right now.

If you find something a little bit cleaner (like alchemydumps), lemme know.
