### ISSUE TITLE
Circular blueprint/view imports

### ISSUE THREAD

**Issue by johnwheffner** [jyundt/oval#31]
Still figuring out framework stuff.  Looking for insight @jyundt @mmaps.

I see for instance `marshal/__init__.py` imports `views` (AFTER creating the Blueprint) in order to use the decorators to register routes.  And `mashal/views.py` imports marshal so that it can register the routes.  This is definitely counter to all Python style guides.  Is this canonical Flask?

**Comment by jyundt** [comment]
I _think_ it is canonical Flask.

I tried fiddling with removing some of the imports and it definitely broke.

Looking at other sample [flask code](https://github.com/miguelgrinberg/flasky/blob/master/app/main/__init__.py) shows something similar:

```
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors
from ..models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)
```

```
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
```

But, I might be missing something as well.

I'm open to any suggestions.

**Comment by jyundt** [comment]
I think I just found the answer from the [Flask website](http://flask.pocoo.org/docs/0.11/patterns/packages/):

> Circular Imports
> Every Python programmer hates them, and yet we just added some: circular imports (That’s when two modules depend on each other. In this case views.py depends on **init**.py). Be advised that this is a bad idea in general but here it is actually fine. The reason for this is that we are not actually using the views in **init**.py and just ensuring the module is imported and we are doing that at the bottom of the file.

**Comment by johnwheffner** [comment]
Thanks for the pointer.  Yeah it's "breaking the rules" but I can see why they're doing it; seems fine if done carefully.
