### ISSUE TITLE
Standings page is broken for 2011 results

### ISSUE THREAD

**Issue by jyundt** [jyundt/oval#54]
Just added the first (non-points) race for 2011.

Somehow it broke the standings page:

![image](https://cloud.githubusercontent.com/assets/5204426/18924757/6489df72-857f-11e6-9efc-dc63ebcedcaa.png)

**Comment by jyundt** [comment]
FWIW, the Results page looks fine:

![image](https://cloud.githubusercontent.com/assets/5204426/18924853/ad4432bc-857f-11e6-98e3-e9f2090896f4.png)

**Comment by johnwheffner** [comment]
The right thing I think is not to allow selecting 2011 standings.

**Comment by jyundt** [comment]
That works for me.

Update: maybe change this query to only include years that have Races with points?

`int(date.year) for (date,) in Race.query.with_entities(Race.date).all()), reverse=True)`

Thoughts?

Yet another update: should have included the actual query

`int(date.year) for (date,) in Race.query.with_entities(Race.date).filter_by(points_race=True).all()), reverse=True)`

**Comment by jyundt** [comment]
FWIW, we would have encountered this same issue when adding the first race of 2017.

Lemme know if PR #55 looks fine.
