### ISSUE TITLE
Display "No results yet" message rather than empty tables on standings/results pages

### ISSUE THREAD

**Issue by johnwheffner** [jyundt/oval#78]
For seasons with no results yet, e.g., right now what we've got 2017 races entered in the calendar but no results because no races have actually happened yet, we're displaying empty tables.  This is ok, but it would look better to say something about not having results yet.

**Comment by jyundt** [comment]
Semi related, the "Recent Results" table on the landing page should only display races that have results:

![image](https://cloud.githubusercontent.com/assets/5204426/24371467/d8fb2698-12f8-11e7-8f3e-e87abe77e391.png)

**Comment by johnwheffner** [comment]
Fixed in #80
